//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   18.1.3 (1ubuntu1)
// 	objdump 2.42
// flags: -O0
// source: tests/src/universal.c

package tests

import "unsafe"

//go:noescape
func add(a, b int64) (result int64)

//go:noescape
func l2(a, b unsafe.Pointer, n int64) (result float32)

//go:noescape
func mat_mul(a, b, res unsafe.Pointer, d1, d2, d3 int64)

//go:noescape
func mul2(a float32) (result float32)

//go:noescape
func _not(a bool) (result bool)

//go:noescape
func sum(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10 int64) (result int64)

//go:noescape
func mul(v1 float32, v2 float64, v3, v4 float32, v5, v6 float64, v7 int64, v8 float64) (result float64)

//go:noescape
func reverse(x1, x2, x3, x4, x5, x6, x7, x8, x9, x10 unsafe.Pointer)
