//go:build !noasm && amd64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   18.1.3 (1ubuntu1)
// 	objdump 2.42
// flags: -O0
// source: tests/src/universal.c

TEXT ·add(SB), $8-16
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	BYTE $0x55                   // pushq	%rbp
	WORD $0x8948; BYTE $0xe5     // movq	%rsp, %rbp
	LONG $0xf8e48348             // andq	$-8, %rsp
	LONG $0x10ec8348             // subq	$16, %rsp
	LONG $0x247c8948; BYTE $0x08 // movq	%rdi, 8(%rsp)
	LONG $0x24348948             // movq	%rsi, (%rsp)
	LONG $0x24448b48; BYTE $0x08 // movq	8(%rsp), %rax
	LONG $0x24040348             // addq	(%rsp), %rax
	WORD $0x8948; BYTE $0xec     // movq	%rbp, %rsp
	BYTE $0x5d                   // popq	%rbp
	MOVQ AX, result+16(FP)
	RET

TEXT ·l2(SB), $8-24
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ n+16(FP), DX
	BYTE $0x55                     // pushq	%rbp
	WORD $0x8948; BYTE $0xe5       // movq	%rsp, %rbp
	LONG $0xf8e48348               // andq	$-8, %rsp
	LONG $0x30ec8348               // subq	$48, %rsp
	LONG $0x247c8948; BYTE $0x28   // movq	%rdi, 40(%rsp)
	LONG $0x24748948; BYTE $0x20   // movq	%rsi, 32(%rsp)
	LONG $0x24548948; BYTE $0x18   // movq	%rdx, 24(%rsp)
	WORD $0x570f; BYTE $0xc0       // xorps	%xmm0, %xmm0
	LONG $0x44110ff3; WORD $0x1424 // movss	%xmm0, 20(%rsp)
	QUAD $0x00000000102444c7       // movl	$0, 16(%rsp)

LBB1_1:
	LONG $0x24446348; BYTE $0x10   // movslq	16(%rsp), %rax
	LONG $0x24443b48; BYTE $0x18   // cmpq	24(%rsp), %rax
	JGE  LBB1_4
	LONG $0x24448b48; BYTE $0x28   // movq	40(%rsp), %rax
	LONG $0x244c6348; BYTE $0x10   // movslq	16(%rsp), %rcx
	LONG $0x04100ff3; BYTE $0x88   // movss	(%rax,%rcx,4), %xmm0            # xmm0 = mem[0],zero,zero,zero
	LONG $0x24448b48; BYTE $0x20   // movq	32(%rsp), %rax
	LONG $0x244c6348; BYTE $0x10   // movslq	16(%rsp), %rcx
	LONG $0x045c0ff3; BYTE $0x88   // subss	(%rax,%rcx,4), %xmm0
	LONG $0x44110ff3; WORD $0x0c24 // movss	%xmm0, 12(%rsp)
	LONG $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG $0x44590ff3; WORD $0x0c24 // mulss	12(%rsp), %xmm0
	LONG $0x44110ff3; WORD $0x0824 // movss	%xmm0, 8(%rsp)
	LONG $0x44100ff3; WORD $0x0824 // movss	8(%rsp), %xmm0                  # xmm0 = mem[0],zero,zero,zero
	LONG $0x44580ff3; WORD $0x1424 // addss	20(%rsp), %xmm0
	LONG $0x44110ff3; WORD $0x1424 // movss	%xmm0, 20(%rsp)
	LONG $0x1024448b               // movl	16(%rsp), %eax
	WORD $0xc083; BYTE $0x01       // addl	$1, %eax
	LONG $0x10244489               // movl	%eax, 16(%rsp)
	JMP  LBB1_1

LBB1_4:
	LONG  $0x44100ff3; WORD $0x1424 // movss	20(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	WORD  $0x8948; BYTE $0xec       // movq	%rbp, %rsp
	BYTE  $0x5d                     // popq	%rbp
	MOVSS X0, result+24(FP)
	RET

TEXT ·mat_mul(SB), $0-48
	MOVQ a+0(FP), DI
	MOVQ b+8(FP), SI
	MOVQ res+16(FP), DX
	MOVQ d1+24(FP), CX
	MOVQ d2+32(FP), R8
	MOVQ d3+40(FP), R9
	BYTE $0x55                   // pushq	%rbp
	WORD $0x8948; BYTE $0xe5     // movq	%rsp, %rbp
	LONG $0xf8e48348             // andq	$-8, %rsp
	LONG $0x40ec8348             // subq	$64, %rsp
	LONG $0x247c8948; BYTE $0x38 // movq	%rdi, 56(%rsp)
	LONG $0x24748948; BYTE $0x30 // movq	%rsi, 48(%rsp)
	LONG $0x24548948; BYTE $0x28 // movq	%rdx, 40(%rsp)
	LONG $0x244c8948; BYTE $0x20 // movq	%rcx, 32(%rsp)
	LONG $0x2444894c; BYTE $0x18 // movq	%r8, 24(%rsp)
	LONG $0x244c894c; BYTE $0x10 // movq	%r9, 16(%rsp)
	QUAD $0x000000000c2444c7     // movl	$0, 12(%rsp)

LBB2_1:
	LONG $0x24446348; BYTE $0x0c // movslq	12(%rsp), %rax
	LONG $0x24443b48; BYTE $0x20 // cmpq	32(%rsp), %rax
	JGE  LBB2_12
	QUAD $0x00000000082444c7     // movl	$0, 8(%rsp)

LBB2_3:
	LONG $0x24446348; BYTE $0x08               // movslq	8(%rsp), %rax
	LONG $0x24443b48; BYTE $0x10               // cmpq	16(%rsp), %rax
	JGE  LBB2_10
	WORD $0x570f; BYTE $0xc0                   // xorps	%xmm0, %xmm0
	LONG $0x44110ff3; WORD $0x0424             // movss	%xmm0, 4(%rsp)
	LONG $0x002404c7; WORD $0x0000; BYTE $0x00 // movl	$0, (%rsp)

LBB2_5:
	LONG $0x24046348               // movslq	(%rsp), %rax
	LONG $0x24443b48; BYTE $0x18   // cmpq	24(%rsp), %rax
	JGE  LBB2_8
	LONG $0x24448b48; BYTE $0x38   // movq	56(%rsp), %rax
	LONG $0x244c6348; BYTE $0x0c   // movslq	12(%rsp), %rcx
	LONG $0x4caf0f48; WORD $0x1824 // imulq	24(%rsp), %rcx
	LONG $0x24146348               // movslq	(%rsp), %rdx
	WORD $0x0148; BYTE $0xd1       // addq	%rdx, %rcx
	LONG $0x04100ff3; BYTE $0x88   // movss	(%rax,%rcx,4), %xmm0            # xmm0 = mem[0],zero,zero,zero
	LONG $0x24448b48; BYTE $0x30   // movq	48(%rsp), %rax
	LONG $0x240c6348               // movslq	(%rsp), %rcx
	LONG $0x4caf0f48; WORD $0x1024 // imulq	16(%rsp), %rcx
	LONG $0x24546348; BYTE $0x08   // movslq	8(%rsp), %rdx
	WORD $0x0148; BYTE $0xd1       // addq	%rdx, %rcx
	LONG $0x14100ff3; BYTE $0x88   // movss	(%rax,%rcx,4), %xmm2            # xmm2 = mem[0],zero,zero,zero
	LONG $0x4c100ff3; WORD $0x0424 // movss	4(%rsp), %xmm1                  # xmm1 = mem[0],zero,zero,zero
	LONG $0xc2590ff3               // mulss	%xmm2, %xmm0
	LONG $0xc1580ff3               // addss	%xmm1, %xmm0
	LONG $0x44110ff3; WORD $0x0424 // movss	%xmm0, 4(%rsp)
	WORD $0x048b; BYTE $0x24       // movl	(%rsp), %eax
	WORD $0xc083; BYTE $0x01       // addl	$1, %eax
	WORD $0x0489; BYTE $0x24       // movl	%eax, (%rsp)
	JMP  LBB2_5

LBB2_8:
	LONG $0x44100ff3; WORD $0x0424 // movss	4(%rsp), %xmm0                  # xmm0 = mem[0],zero,zero,zero
	LONG $0x24448b48; BYTE $0x28   // movq	40(%rsp), %rax
	LONG $0x244c6348; BYTE $0x0c   // movslq	12(%rsp), %rcx
	LONG $0x4caf0f48; WORD $0x1024 // imulq	16(%rsp), %rcx
	LONG $0x24546348; BYTE $0x08   // movslq	8(%rsp), %rdx
	WORD $0x0148; BYTE $0xd1       // addq	%rdx, %rcx
	LONG $0x04110ff3; BYTE $0x88   // movss	%xmm0, (%rax,%rcx,4)
	LONG $0x0824448b               // movl	8(%rsp), %eax
	WORD $0xc083; BYTE $0x01       // addl	$1, %eax
	LONG $0x08244489               // movl	%eax, 8(%rsp)
	JMP  LBB2_3

LBB2_10:
	JMP LBB2_11

LBB2_11:
	LONG $0x0c24448b         // movl	12(%rsp), %eax
	WORD $0xc083; BYTE $0x01 // addl	$1, %eax
	LONG $0x0c244489         // movl	%eax, 12(%rsp)
	JMP  LBB2_1

LBB2_12:
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	RET

TEXT ·mul2(SB), $8-8
	MOVSS a+0(FP), X0
	BYTE  $0x55                     // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5       // movq	%rsp, %rbp
	LONG  $0xf8e48348               // andq	$-8, %rsp
	LONG  $0x10ec8348               // subq	$16, %rsp
	LONG  $0x44110ff3; WORD $0x0424 // movss	%xmm0, 4(%rsp)
	LONG  $0x4c100ff3; WORD $0x0424 // movss	4(%rsp), %xmm1                  # xmm1 = mem[0],zero,zero,zero
	LONG  $0x44100ff3; WORD $0x0424 // movss	4(%rsp), %xmm0                  # xmm0 = mem[0],zero,zero,zero
	LONG  $0x4c110ff3; WORD $0x0c24 // movss	%xmm1, 12(%rsp)
	LONG  $0x44110ff3; WORD $0x0824 // movss	%xmm0, 8(%rsp)
	LONG  $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0x44580ff3; WORD $0x0824 // addss	8(%rsp), %xmm0
	WORD  $0x8948; BYTE $0xec       // movq	%rbp, %rsp
	BYTE  $0x5d                     // popq	%rbp
	MOVSS X0, result+8(FP)
	RET

TEXT ·_not(SB), $8-8
	MOVQ a+0(FP), DI
	BYTE $0x55               // pushq	%rbp
	WORD $0x8948; BYTE $0xe5 // movq	%rsp, %rbp
	LONG $0xf8e48348         // andq	$-8, %rsp
	LONG $0x10ec8348         // subq	$16, %rsp
	WORD $0x8840; BYTE $0xf8 // movb	%dil, %al
	WORD $0x0124             // andb	$1, %al
	LONG $0x0f244488         // movb	%al, 15(%rsp)
	LONG $0x0f24448a         // movb	15(%rsp), %al
	WORD $0xff34             // xorb	$-1, %al
	WORD $0x0124             // andb	$1, %al
	WORD $0xb60f; BYTE $0xc0 // movzbl	%al, %eax
	WORD $0x8948; BYTE $0xec // movq	%rbp, %rsp
	BYTE $0x5d               // popq	%rbp
	MOVQ AX, result+8(FP)
	RET

TEXT ·sum(SB), $8-80
	MOVQ  x1+0(FP), DI
	MOVQ  x2+8(FP), SI
	MOVQ  x3+16(FP), DX
	MOVQ  x4+24(FP), CX
	MOVQ  x5+32(FP), R8
	MOVQ  x6+40(FP), R9
	PUSHQ x10+72(FP)
	PUSHQ x9+64(FP)
	PUSHQ x8+56(FP)
	PUSHQ x7+48(FP)
	PUSHQ $0
	BYTE  $0x55                   // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5     // movq	%rsp, %rbp
	LONG  $0xf8e48348             // andq	$-8, %rsp
	LONG  $0x30ec8348             // subq	$48, %rsp
	LONG  $0x28458b48             // movq	40(%rbp), %rax
	LONG  $0x20458b48             // movq	32(%rbp), %rax
	LONG  $0x18458b48             // movq	24(%rbp), %rax
	LONG  $0x10458b48             // movq	16(%rbp), %rax
	LONG  $0x247c8948; BYTE $0x28 // movq	%rdi, 40(%rsp)
	LONG  $0x24748948; BYTE $0x20 // movq	%rsi, 32(%rsp)
	LONG  $0x24548948; BYTE $0x18 // movq	%rdx, 24(%rsp)
	LONG  $0x244c8948; BYTE $0x10 // movq	%rcx, 16(%rsp)
	LONG  $0x2444894c; BYTE $0x08 // movq	%r8, 8(%rsp)
	LONG  $0x240c894c             // movq	%r9, (%rsp)
	LONG  $0x24448b48; BYTE $0x28 // movq	40(%rsp), %rax
	LONG  $0x24440348; BYTE $0x20 // addq	32(%rsp), %rax
	LONG  $0x24440348; BYTE $0x18 // addq	24(%rsp), %rax
	LONG  $0x24440348; BYTE $0x10 // addq	16(%rsp), %rax
	LONG  $0x24440348; BYTE $0x08 // addq	8(%rsp), %rax
	LONG  $0x24040348             // addq	(%rsp), %rax
	LONG  $0x10450348             // addq	16(%rbp), %rax
	LONG  $0x18450348             // addq	24(%rbp), %rax
	LONG  $0x20450348             // addq	32(%rbp), %rax
	LONG  $0x28450348             // addq	40(%rbp), %rax
	WORD  $0x8948; BYTE $0xec     // movq	%rbp, %rsp
	BYTE  $0x5d                   // popq	%rbp
	POPQ  DI
	POPQ  DI
	POPQ  DI
	POPQ  DI
	POPQ  DI
	MOVQ  AX, result+80(FP)
	RET

TEXT ·mul(SB), $8-64
	MOVSS v1+0(FP), X0
	MOVSD v2+8(FP), X1
	MOVSS v3+16(FP), X2
	MOVSS v4+20(FP), X3
	MOVSD v5+24(FP), X4
	MOVSD v6+32(FP), X5
	MOVQ  v7+40(FP), DI
	MOVSD v8+48(FP), X6
	BYTE  $0x55                                 // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5                   // movq	%rsp, %rbp
	LONG  $0xf8e48348                           // andq	$-8, %rsp
	LONG  $0x40ec8348                           // subq	$64, %rsp
	LONG  $0x44110ff3; WORD $0x3c24             // movss	%xmm0, 60(%rsp)
	LONG  $0x4c110ff2; WORD $0x3024             // movsd	%xmm1, 48(%rsp)
	LONG  $0x54110ff3; WORD $0x2c24             // movss	%xmm2, 44(%rsp)
	LONG  $0x5c110ff3; WORD $0x2824             // movss	%xmm3, 40(%rsp)
	LONG  $0x64110ff2; WORD $0x2024             // movsd	%xmm4, 32(%rsp)
	LONG  $0x6c110ff2; WORD $0x1824             // movsd	%xmm5, 24(%rsp)
	LONG  $0x247c8948; BYTE $0x10               // movq	%rdi, 16(%rsp)
	LONG  $0x74110ff2; WORD $0x0824             // movsd	%xmm6, 8(%rsp)
	LONG  $0x44100ff3; WORD $0x3c24             // movss	60(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0xc05a0ff3                           // cvtss2sd	%xmm0, %xmm0
	LONG  $0x44590ff2; WORD $0x3024             // mulsd	48(%rsp), %xmm0
	LONG  $0x4c100ff3; WORD $0x2c24             // movss	44(%rsp), %xmm1                 # xmm1 = mem[0],zero,zero,zero
	LONG  $0xc95a0ff3                           // cvtss2sd	%xmm1, %xmm1
	LONG  $0xc1590ff2                           // mulsd	%xmm1, %xmm0
	LONG  $0x4c100ff3; WORD $0x2824             // movss	40(%rsp), %xmm1                 # xmm1 = mem[0],zero,zero,zero
	LONG  $0xc95a0ff3                           // cvtss2sd	%xmm1, %xmm1
	LONG  $0xc1590ff2                           // mulsd	%xmm1, %xmm0
	LONG  $0x44590ff2; WORD $0x2024             // mulsd	32(%rsp), %xmm0
	LONG  $0x44590ff2; WORD $0x1824             // mulsd	24(%rsp), %xmm0
	LONG  $0x2a0f48f2; WORD $0x244c; BYTE $0x10 // cvtsi2sdq	16(%rsp), %xmm1
	LONG  $0xc1590ff2                           // mulsd	%xmm1, %xmm0
	LONG  $0x44590ff2; WORD $0x0824             // mulsd	8(%rsp), %xmm0
	WORD  $0x8948; BYTE $0xec                   // movq	%rbp, %rsp
	BYTE  $0x5d                                 // popq	%rbp
	MOVSD X0, result+56(FP)
	RET

TEXT ·reverse(SB), $0-80
	MOVQ  x1+0(FP), DI
	MOVQ  x2+8(FP), SI
	MOVQ  x3+16(FP), DX
	MOVQ  x4+24(FP), CX
	MOVQ  x5+32(FP), R8
	MOVQ  x6+40(FP), R9
	PUSHQ x10+72(FP)
	PUSHQ x9+64(FP)
	PUSHQ x8+56(FP)
	PUSHQ x7+48(FP)
	PUSHQ $0
	BYTE  $0x55                     // pushq	%rbp
	WORD  $0x8948; BYTE $0xe5       // movq	%rsp, %rbp
	LONG  $0xf8e48348               // andq	$-8, %rsp
	LONG  $0x40ec8348               // subq	$64, %rsp
	LONG  $0x28458b48               // movq	40(%rbp), %rax
	LONG  $0x20458b48               // movq	32(%rbp), %rax
	LONG  $0x18458b48               // movq	24(%rbp), %rax
	LONG  $0x10458b48               // movq	16(%rbp), %rax
	LONG  $0x247c8948; BYTE $0x38   // movq	%rdi, 56(%rsp)
	LONG  $0x24748948; BYTE $0x30   // movq	%rsi, 48(%rsp)
	LONG  $0x24548948; BYTE $0x28   // movq	%rdx, 40(%rsp)
	LONG  $0x244c8948; BYTE $0x20   // movq	%rcx, 32(%rsp)
	LONG  $0x2444894c; BYTE $0x18   // movq	%r8, 24(%rsp)
	LONG  $0x244c894c; BYTE $0x10   // movq	%r9, 16(%rsp)
	LONG  $0x24448b48; BYTE $0x38   // movq	56(%rsp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x44110ff3; WORD $0x0c24 // movss	%xmm0, 12(%rsp)
	LONG  $0x28458b48               // movq	40(%rbp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x24448b48; BYTE $0x38   // movq	56(%rsp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0x28458b48               // movq	40(%rbp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x24448b48; BYTE $0x30   // movq	48(%rsp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x44110ff3; WORD $0x0c24 // movss	%xmm0, 12(%rsp)
	LONG  $0x20458b48               // movq	32(%rbp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x24448b48; BYTE $0x30   // movq	48(%rsp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0x20458b48               // movq	32(%rbp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x24448b48; BYTE $0x28   // movq	40(%rsp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x44110ff3; WORD $0x0c24 // movss	%xmm0, 12(%rsp)
	LONG  $0x18458b48               // movq	24(%rbp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x24448b48; BYTE $0x28   // movq	40(%rsp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0x18458b48               // movq	24(%rbp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x24448b48; BYTE $0x20   // movq	32(%rsp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x44110ff3; WORD $0x0c24 // movss	%xmm0, 12(%rsp)
	LONG  $0x10458b48               // movq	16(%rbp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x24448b48; BYTE $0x20   // movq	32(%rsp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0x10458b48               // movq	16(%rbp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x24448b48; BYTE $0x18   // movq	24(%rsp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x44110ff3; WORD $0x0c24 // movss	%xmm0, 12(%rsp)
	LONG  $0x24448b48; BYTE $0x10   // movq	16(%rsp), %rax
	LONG  $0x00100ff3               // movss	(%rax), %xmm0                   # xmm0 = mem[0],zero,zero,zero
	LONG  $0x24448b48; BYTE $0x18   // movq	24(%rsp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	LONG  $0x44100ff3; WORD $0x0c24 // movss	12(%rsp), %xmm0                 # xmm0 = mem[0],zero,zero,zero
	LONG  $0x24448b48; BYTE $0x10   // movq	16(%rsp), %rax
	LONG  $0x00110ff3               // movss	%xmm0, (%rax)
	WORD  $0x8948; BYTE $0xec       // movq	%rbp, %rsp
	BYTE  $0x5d                     // popq	%rbp
	POPQ  DI
	POPQ  DI
	POPQ  DI
	POPQ  DI
	POPQ  DI
	RET
