//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.2
// 	objdump 2.45
// flags: -O0
// source: tests/src/universal.c

TEXT ·add(SB), $16-24
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	WORD $0xd10043ff       // sub	sp, sp, #16
	WORD $0xf90007e0       // str	x0, [sp, #8]
	WORD $0xf90003e1       // str	x1, [sp]
	WORD $0xf94007e8       // ldr	x8, [sp, #8]
	WORD $0xf94003e9       // ldr	x9, [sp]
	WORD $0x8b090100       // add	x0, x8, x9
	WORD $0x910043ff       // add	sp, sp, #16
	MOVD R0, result+16(FP)
	RET

TEXT ·l2(SB), $48-28
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD n+16(FP), R2
	WORD $0xd100c3ff  // sub	sp, sp, #48
	WORD $0xf90017e0  // str	x0, [sp, #40]
	WORD $0xf90013e1  // str	x1, [sp, #32]
	WORD $0xf9000fe2  // str	x2, [sp, #24]
	WORD $0x2f00e400  // movi	d0, #0000000000000000
	WORD $0xbd0017e0  // str	s0, [sp, #20]
	WORD $0xb90013ff  // str	wzr, [sp, #16]
	B    LBB1_1

LBB1_1:
	WORD $0xb98013e8 // ldrsw	x8, [sp, #16]
	WORD $0xf9400fe9 // ldr	x9, [sp, #24]
	WORD $0xeb090108 // subs	x8, x8, x9
	BGE  LBB1_4
	B    LBB1_2

LBB1_2:
	WORD $0xf94017e8 // ldr	x8, [sp, #40]
	WORD $0xb98013e9 // ldrsw	x9, [sp, #16]
	WORD $0xbc697900 // ldr	s0, [x8, x9, lsl #2]
	WORD $0xf94013e8 // ldr	x8, [sp, #32]
	WORD $0xb98013e9 // ldrsw	x9, [sp, #16]
	WORD $0xbc697901 // ldr	s1, [x8, x9, lsl #2]
	WORD $0x1e213800 // fsub	s0, s0, s1
	WORD $0xbd000fe0 // str	s0, [sp, #12]
	WORD $0xbd400fe0 // ldr	s0, [sp, #12]
	WORD $0xbd400fe1 // ldr	s1, [sp, #12]
	WORD $0x1e210800 // fmul	s0, s0, s1
	WORD $0xbd000be0 // str	s0, [sp, #8]
	WORD $0xbd400be1 // ldr	s1, [sp, #8]
	WORD $0xbd4017e0 // ldr	s0, [sp, #20]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0xbd0017e0 // str	s0, [sp, #20]
	B    LBB1_3

LBB1_3:
	WORD $0xb94013e8 // ldr	w8, [sp, #16]
	WORD $0x11000508 // add	w8, w8, #1
	WORD $0xb90013e8 // str	w8, [sp, #16]
	B    LBB1_1

LBB1_4:
	WORD  $0xbd4017e0       // ldr	s0, [sp, #20]
	WORD  $0x9100c3ff       // add	sp, sp, #48
	FMOVS F0, result+24(FP)
	RET

TEXT ·mat_mul(SB), $64-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD res+16(FP), R2
	MOVD d1+24(FP), R3
	MOVD d2+32(FP), R4
	MOVD d3+40(FP), R5
	WORD $0xd10103ff    // sub	sp, sp, #64
	WORD $0xf9001fe0    // str	x0, [sp, #56]
	WORD $0xf9001be1    // str	x1, [sp, #48]
	WORD $0xf90017e2    // str	x2, [sp, #40]
	WORD $0xf90013e3    // str	x3, [sp, #32]
	WORD $0xf9000fe4    // str	x4, [sp, #24]
	WORD $0xf9000be5    // str	x5, [sp, #16]
	WORD $0xb9000fff    // str	wzr, [sp, #12]
	B    LBB2_1

LBB2_1:
	WORD $0xb9800fe8 // ldrsw	x8, [sp, #12]
	WORD $0xf94013e9 // ldr	x9, [sp, #32]
	WORD $0xeb090108 // subs	x8, x8, x9
	BGE  LBB2_12
	B    LBB2_2

LBB2_2:
	WORD $0xb9000bff // str	wzr, [sp, #8]
	B    LBB2_3

LBB2_3:
	WORD $0xb9800be8 // ldrsw	x8, [sp, #8]
	WORD $0xf9400be9 // ldr	x9, [sp, #16]
	WORD $0xeb090108 // subs	x8, x8, x9
	BGE  LBB2_10
	B    LBB2_4

LBB2_4:
	WORD $0x2f00e400 // movi	d0, #0000000000000000
	WORD $0xbd0007e0 // str	s0, [sp, #4]
	WORD $0xb90003ff // str	wzr, [sp]
	B    LBB2_5

LBB2_5:
	WORD $0xb98003e8 // ldrsw	x8, [sp]
	WORD $0xf9400fe9 // ldr	x9, [sp, #24]
	WORD $0xeb090108 // subs	x8, x8, x9
	BGE  LBB2_8
	B    LBB2_6

LBB2_6:
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]
	WORD $0xb9800fe9 // ldrsw	x9, [sp, #12]
	WORD $0xf9400fea // ldr	x10, [sp, #24]
	WORD $0x9b0a7d29 // mul	x9, x9, x10
	WORD $0xb98003ea // ldrsw	x10, [sp]
	WORD $0x8b0a0129 // add	x9, x9, x10
	WORD $0xbc697900 // ldr	s0, [x8, x9, lsl #2]
	WORD $0xf9401be8 // ldr	x8, [sp, #48]
	WORD $0xb98003e9 // ldrsw	x9, [sp]
	WORD $0xf9400bea // ldr	x10, [sp, #16]
	WORD $0x9b0a7d29 // mul	x9, x9, x10
	WORD $0xb9800bea // ldrsw	x10, [sp, #8]
	WORD $0x8b0a0129 // add	x9, x9, x10
	WORD $0xbc697901 // ldr	s1, [x8, x9, lsl #2]
	WORD $0xbd4007e2 // ldr	s2, [sp, #4]
	WORD $0x1f010800 // fmadd	s0, s0, s1, s2
	WORD $0xbd0007e0 // str	s0, [sp, #4]
	B    LBB2_7

LBB2_7:
	WORD $0xb94003e8 // ldr	w8, [sp]
	WORD $0x11000508 // add	w8, w8, #1
	WORD $0xb90003e8 // str	w8, [sp]
	B    LBB2_5

LBB2_8:
	WORD $0xbd4007e0 // ldr	s0, [sp, #4]
	WORD $0xf94017e8 // ldr	x8, [sp, #40]
	WORD $0xb9800fe9 // ldrsw	x9, [sp, #12]
	WORD $0xf9400bea // ldr	x10, [sp, #16]
	WORD $0x9b0a7d29 // mul	x9, x9, x10
	WORD $0xb9800bea // ldrsw	x10, [sp, #8]
	WORD $0x8b0a0129 // add	x9, x9, x10
	WORD $0xbc297900 // str	s0, [x8, x9, lsl #2]
	B    LBB2_9

LBB2_9:
	WORD $0xb9400be8 // ldr	w8, [sp, #8]
	WORD $0x11000508 // add	w8, w8, #1
	WORD $0xb9000be8 // str	w8, [sp, #8]
	B    LBB2_3

LBB2_10:
	B LBB2_11

LBB2_11:
	WORD $0xb9400fe8 // ldr	w8, [sp, #12]
	WORD $0x11000508 // add	w8, w8, #1
	WORD $0xb9000fe8 // str	w8, [sp, #12]
	B    LBB2_1

LBB2_12:
	WORD $0x910103ff // add	sp, sp, #64
	RET

TEXT ·mul2(SB), $16-12
	FMOVS a+0(FP), F0
	WORD  $0xd10043ff      // sub	sp, sp, #16
	WORD  $0xbd0007e0      // str	s0, [sp, #4]
	WORD  $0xbd4007e1      // ldr	s1, [sp, #4]
	WORD  $0xbd4007e0      // ldr	s0, [sp, #4]
	WORD  $0xbd000fe1      // str	s1, [sp, #12]
	WORD  $0xbd000be0      // str	s0, [sp, #8]
	WORD  $0xbd400fe0      // ldr	s0, [sp, #12]
	WORD  $0xbd400be1      // ldr	s1, [sp, #8]
	WORD  $0x1e212800      // fadd	s0, s0, s1
	WORD  $0x910043ff      // add	sp, sp, #16
	FMOVS F0, result+8(FP)
	RET

TEXT ·_not(SB), $16-9
	MOVD a+0(FP), R0
	WORD $0xd10043ff      // sub	sp, sp, #16
	WORD $0x39003fe0      // strb	w0, [sp, #15]
	WORD $0x39403fe8      // ldrb	w8, [sp, #15]
	WORD $0x52000108      // eor	w8, w8, #0x1
	WORD $0x12000100      // and	w0, w8, #0x1
	WORD $0x910043ff      // add	sp, sp, #16
	MOVD R0, result+8(FP)
	RET

TEXT ·sum(SB), $80-88
	MOVD x1+0(FP), R0
	MOVD x2+8(FP), R1
	MOVD x3+16(FP), R2
	MOVD x4+24(FP), R3
	MOVD x5+32(FP), R4
	MOVD x6+40(FP), R5
	MOVD x7+48(FP), R6
	MOVD x8+56(FP), R7
	MOVD x9+64(FP), R8
	MOVD R8, 0(RSP)
	MOVD x10+72(FP), R8
	MOVD R8, 8(RSP)
	WORD $0xd10143ff       // sub	sp, sp, #80
	WORD $0xf9402be9       // ldr	x9, [sp, #80]
	WORD $0xf9402fe8       // ldr	x8, [sp, #88]
	WORD $0xf90027e0       // str	x0, [sp, #72]
	WORD $0xf90023e1       // str	x1, [sp, #64]
	WORD $0xf9001fe2       // str	x2, [sp, #56]
	WORD $0xf9001be3       // str	x3, [sp, #48]
	WORD $0xf90017e4       // str	x4, [sp, #40]
	WORD $0xf90013e5       // str	x5, [sp, #32]
	WORD $0xf9000fe6       // str	x6, [sp, #24]
	WORD $0xf9000be7       // str	x7, [sp, #16]
	WORD $0xf90007e9       // str	x9, [sp, #8]
	WORD $0xf90003e8       // str	x8, [sp]
	WORD $0xf94027e8       // ldr	x8, [sp, #72]
	WORD $0xf94023e9       // ldr	x9, [sp, #64]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf9401fe9       // ldr	x9, [sp, #56]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf9401be9       // ldr	x9, [sp, #48]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf94017e9       // ldr	x9, [sp, #40]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf94013e9       // ldr	x9, [sp, #32]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf9400fe9       // ldr	x9, [sp, #24]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf9400be9       // ldr	x9, [sp, #16]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf94007e9       // ldr	x9, [sp, #8]
	WORD $0x8b090108       // add	x8, x8, x9
	WORD $0xf94003e9       // ldr	x9, [sp]
	WORD $0x8b090100       // add	x0, x8, x9
	WORD $0x910143ff       // add	sp, sp, #80
	MOVD R0, result+80(FP)
	RET

TEXT ·mul(SB), $64-64
	FMOVS v1+0(FP), F0
	FMOVD v2+8(FP), F1
	FMOVS v3+16(FP), F2
	FMOVS v4+20(FP), F3
	FMOVD v5+24(FP), F4
	FMOVD v6+32(FP), F5
	MOVD  v7+40(FP), R0
	FMOVD v8+48(FP), F6
	WORD  $0xd10103ff       // sub	sp, sp, #64
	WORD  $0xbd003fe0       // str	s0, [sp, #60]
	WORD  $0xfd001be1       // str	d1, [sp, #48]
	WORD  $0xbd002fe2       // str	s2, [sp, #44]
	WORD  $0xbd002be3       // str	s3, [sp, #40]
	WORD  $0xfd0013e4       // str	d4, [sp, #32]
	WORD  $0xfd000fe5       // str	d5, [sp, #24]
	WORD  $0xf9000be0       // str	x0, [sp, #16]
	WORD  $0xfd0007e6       // str	d6, [sp, #8]
	WORD  $0xbd403fe0       // ldr	s0, [sp, #60]
	WORD  $0x1e22c000       // fcvt	d0, s0
	WORD  $0xfd401be1       // ldr	d1, [sp, #48]
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0xbd402fe1       // ldr	s1, [sp, #44]
	WORD  $0x1e22c021       // fcvt	d1, s1
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0xbd402be1       // ldr	s1, [sp, #40]
	WORD  $0x1e22c021       // fcvt	d1, s1
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0xfd4013e1       // ldr	d1, [sp, #32]
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0xfd400fe1       // ldr	d1, [sp, #24]
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0xfd400be1       // ldr	d1, [sp, #16]
	WORD  $0x5e61d821       // scvtf	d1, d1
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0xfd4007e1       // ldr	d1, [sp, #8]
	WORD  $0x1e610800       // fmul	d0, d0, d1
	WORD  $0x910103ff       // add	sp, sp, #64
	FMOVD F0, result+56(FP)
	RET

TEXT ·reverse(SB), $96-80
	MOVD x1+0(FP), R0
	MOVD x2+8(FP), R1
	MOVD x3+16(FP), R2
	MOVD x4+24(FP), R3
	MOVD x5+32(FP), R4
	MOVD x6+40(FP), R5
	MOVD x7+48(FP), R6
	MOVD x8+56(FP), R7
	MOVD x9+64(FP), R8
	MOVD R8, 0(RSP)
	MOVD x10+72(FP), R8
	MOVD R8, 8(RSP)
	WORD $0xd10183ff    // sub	sp, sp, #96
	WORD $0xf94033e9    // ldr	x9, [sp, #96]
	WORD $0xf94037e8    // ldr	x8, [sp, #104]
	WORD $0xf9002fe0    // str	x0, [sp, #88]
	WORD $0xf9002be1    // str	x1, [sp, #80]
	WORD $0xf90027e2    // str	x2, [sp, #72]
	WORD $0xf90023e3    // str	x3, [sp, #64]
	WORD $0xf9001fe4    // str	x4, [sp, #56]
	WORD $0xf9001be5    // str	x5, [sp, #48]
	WORD $0xf90017e6    // str	x6, [sp, #40]
	WORD $0xf90013e7    // str	x7, [sp, #32]
	WORD $0xf9000fe9    // str	x9, [sp, #24]
	WORD $0xf9000be8    // str	x8, [sp, #16]
	WORD $0xf9402fe8    // ldr	x8, [sp, #88]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xbd000fe0    // str	s0, [sp, #12]
	WORD $0xf9400be8    // ldr	x8, [sp, #16]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xf9402fe8    // ldr	x8, [sp, #88]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xbd400fe0    // ldr	s0, [sp, #12]
	WORD $0xf9400be8    // ldr	x8, [sp, #16]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xf9402be8    // ldr	x8, [sp, #80]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xbd000fe0    // str	s0, [sp, #12]
	WORD $0xf9400fe8    // ldr	x8, [sp, #24]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xf9402be8    // ldr	x8, [sp, #80]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xbd400fe0    // ldr	s0, [sp, #12]
	WORD $0xf9400fe8    // ldr	x8, [sp, #24]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xf94027e8    // ldr	x8, [sp, #72]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xbd000fe0    // str	s0, [sp, #12]
	WORD $0xf94013e8    // ldr	x8, [sp, #32]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xf94027e8    // ldr	x8, [sp, #72]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xbd400fe0    // ldr	s0, [sp, #12]
	WORD $0xf94013e8    // ldr	x8, [sp, #32]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xf94023e8    // ldr	x8, [sp, #64]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xbd000fe0    // str	s0, [sp, #12]
	WORD $0xf94017e8    // ldr	x8, [sp, #40]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xf94023e8    // ldr	x8, [sp, #64]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xbd400fe0    // ldr	s0, [sp, #12]
	WORD $0xf94017e8    // ldr	x8, [sp, #40]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xf9401fe8    // ldr	x8, [sp, #56]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xbd000fe0    // str	s0, [sp, #12]
	WORD $0xf9401be8    // ldr	x8, [sp, #48]
	WORD $0xbd400100    // ldr	s0, [x8]
	WORD $0xf9401fe8    // ldr	x8, [sp, #56]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0xbd400fe0    // ldr	s0, [sp, #12]
	WORD $0xf9401be8    // ldr	x8, [sp, #48]
	WORD $0xbd000100    // str	s0, [x8]
	WORD $0x910183ff    // add	sp, sp, #96
	RET
