version: 2.1

jobs:
  test-arm64:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y clang
      - run:
          name: Install GOAT
          command: go install .
      - run:
          name: Run tests
          command: |
            goat tests/src/universal.c -o tests
            go test -v ./tests

workflows:
  test:
    jobs:
      - test-arm64
