name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
      - name: Install clang
        uses: ConorMacBride/install-package@v1
        with:
          apt: clang libc6-dev-i386
      - name: Install GOAT
        run: go install .
      - name: Run tests
        run: |
          goat tests/src/universal.c -o tests
          go test -C ./tests -v

  arm:
    name: ubuntu-24.04-arm
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
      - name: Install clang
        uses: ConorMacBride/install-package@v1
        with:
          apt: clang
      - name: Install GOAT
        run: go install .
      - name: Run tests
        run: |
          goat tests/src/universal.c -o tests
          go test -C ./tests -v

  macos:
    name: macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install clang and binutils
        run: brew install llvm binutils
      - name: Install GOAT
        run: go install .
      - name: Run tests
        run: |
          export PATH=/opt/homebrew/opt/llvm/bin:$PATH
          export PATH=/opt/homebrew/opt/binutils/bin:$PATH
          goat tests/src/universal.c -o tests
          go test -C ./tests -v

  windows:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
      - name: Install LLVM and MinGW-w64
        uses: ConorMacBride/install-package@v1
        with:
          choco: llvm mingw
      - name: Install GOAT
        run: go install .
      - name: Run tests
        run: |
          goat tests/src/universal.c -o tests
          go test -C ./tests -v

  riscv:
    name: qemu-riscv64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          apt: qemu-user-static clang lld binutils-riscv64-linux-gnu gcc-riscv64-linux-gnu g++-riscv64-linux-gnu
      - name: Cross-compile GOAT for RISC-V
        run: GOOS=linux GOARCH=riscv64 CGO_ENABLED=0 go build -o goat .
      - name: Generate RISC-V assembly with GOAT
        env:
          CC: riscv64-linux-gnu-gcc
          CXX: riscv64-linux-gnu-g++
          QEMU_LD_PREFIX: /usr/riscv64-linux-gnu
          OBJDUMP: /usr/bin/riscv64-linux-gnu-objdump
          CLANG: /usr/bin/clang
        run: qemu-riscv64-static ./goat tests/src/universal.c -o tests -march=rv64imafd
      - name: Run tests with QEMU
        env:
          QEMU_LD_PREFIX: /usr/riscv64-linux-gnu
        run: |
          cd tests
          GOOS=linux GOARCH=riscv64 CGO_ENABLED=0 go test -c -o tests.test
          qemu-riscv64-static ./tests.test -test.v

  loong64:
    name: qemu-loong64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          apt: qemu-user-static clang lld binutils-loongarch64-linux-gnu gcc-14-loongarch64-linux-gnu g++-14-loongarch64-linux-gnu
      - name: Cross-compile GOAT for LoongArch
        run: GOOS=linux GOARCH=loong64 CGO_ENABLED=0 go build -o goat .
      - name: Generate LoongArch assembly with GOAT
        env:
          CC: loongarch64-linux-gnu-gcc-14
          CXX: loongarch64-linux-gnu-g++-14
          QEMU_LD_PREFIX: /usr/loongarch64-linux-gnu
          OBJDUMP: /usr/bin/loongarch64-linux-gnu-objdump
          CLANG: /usr/bin/clang
        run: qemu-loongarch64-static ./goat tests/src/universal.c -o tests
      - name: Run tests with QEMU
        env:
          QEMU_LD_PREFIX: /usr/loongarch64-linux-gnu
        run: |
          cd tests
          GOOS=linux GOARCH=loong64 CGO_ENABLED=0 go test -c -o tests.test
          qemu-loongarch64-static ./tests.test -test.v
